server:
  port: 20000


spring:
  cloud:
     config:
       server:
         git:
           uri: https://github.com/sesanp4/common-config-server.git
  application:
    name: common-config-server


#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
##          searchLocations: 'classpath:/configs/{application}'
#          search-paths: '/src/main/resources/configs/{application}'


